### ISSUE TITLE
Pass region as config to minio client to support s3 bucket as storage

### ISSUE THREAD

**Issue by johannesf95** [NiklasPor/nx-remotecache-minio#3]
Hi, first of all thanks for providing these options to use custom cache storage providers! 
I really would like to use this lib with a s3 bucket, but during testing, I got the following error:
![image](https://user-images.githubusercontent.com/44813236/147135845-327dddb5-c96d-4ab6-8cd0-7071d9ac2269.png)
I think this could be fixed by passing a region to the minio client constructor optionally, which could be retrieved from nx.json or env like the other options.
If I find time, I might open a pull-request in the next days to add this option.

**Comment by NiklasPor** [comment]
Thanks for your contribution!
Now available in version: `nx-remotecache-minio@1.1.0` 🚀
