### ISSUE TITLE
(node:280998) MaxListenersExceededWarning

### ISSUE THREAD

**Issue by ZeekoZhu** [NiklasPor/nx-remotecache-minio#5]
When using this task runner with node v16.16.0, it shows the below warnings:

```
(node:280998) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 Symbol(destroyed) listener
```

**Comment by mmontes-goldenrace** [comment]
Same situation with node 18.10.0

```
(node:34) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 Symbol(destroyed) listeners added to [Pack]. Use emitter.setMaxListeners() to increase limit
```

**Comment by NiklasPor** [comment]
Hey all, I suspect we solved this with some other changes a while ago. Is this still occuring for anyone of you (with the latest versions)? If yes, this is an minio-only bug and I'd suspect it would be connected to the minio package.

**Comment by ZeekoZhu** [comment]
I can confirm that the issue hasn't occurred for me in a while. I've been using the latest versions, and everything has been running smoothly. It seems likely that the recent changes have resolved it, at least in my case.
