### ISSUE TITLE
Plugin breaks nx serve after update to nx 17.3

### ISSUE THREAD

**Issue by SnakeSVx** [NiklasPor/nx-remotecache-minio#9]
This plugin seems to break the ability to stop command's like nx serve after the update of nx to 17.3.

Build, lint, ... all (cachable) seems to work fine, but serve (which is not cacheable), can't be "stopped" anymore in the regular way.

**Comment by SnakeSVx** [comment]
There is an issue on the nx repo as well for this. Seems like this plugin is not the only one affected: 

https://github.com/nrwl/nx/issues/21523

**Comment by bojanbass** [comment]
+1

**Comment by NiklasPor** [comment]
Hey, let's track this in the general repository, as this is not specific to the minio variant: https://github.com/NiklasPor/nx-remotecache-custom/issues/37
